// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjhdibqfsiqlsmkpkkhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqaGRpYnFmc2lxbHNta3Bra2huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwMjcxNjYsImV4cCI6MjA5MTYwMzE2Nn0.60uQCXFp90hGa4ds8b12NE1DIfKJzqvVh6BsN4KHGLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});